### PR TITLE
Add reading list blogpost

### PR DESCRIPTION
**Pull request by jfranciscosousa**

### CODE REVIEW

**Comment by ines-silva** [comment]
This img with full width pls
Screenshot 2019-10-30 at 12 02 20

I've updated the docs with amazon links for all books and a H3 to "Recommended by (...)" 
https://docs.google.com/document/d/1t46oqOrvaAhnpoYbGEUsgYyKgDNjebw06MG86RGh1tg/edit#heading=h.y2hy9sj0q9tl

**Comment by jfranciscosousa** [comment]
@ines-silva I don't think I can..... that's because of the image aspect ratio. Only way is to find a larger image maybe.

**Comment by jfranciscosousa** [comment]
Closed in favor of #216

**Comment by ines-silva** [comment]
Looks good ✅

**Pull request closed without merging**
