### PR TITLE
Update services section

### PR DESCRIPTION
**Pull request by taniaprocha**

### CODE REVIEW

**Comment by taniaprocha** [comment]
Design review ✅

**Comment by filipebfernandes** [comment]
@taniaprocha is this mobile ready?

**Comment by taniaprocha** [comment]
> @taniaprocha is this mobile ready?

Yes. Click to view cards in mobile, hover to view cards in desktop.

**Comment by filipebfernandes** [comment]
ok. I have some concerns regarding this section, maybe this needs to be discussed with inês as well.

1. how is this working in terms of accessibility?
1. On mobile, you don't normally click on images unless they look like having some kind of interaction. Personally I would never click on one.

**Comment by zediogoviana** [comment]
Using @filipebfernandes second concern, I tried the mobile version and noticed that something has a width bigger than the viewport size (you can scroll right exceeding the normal window size, but there is nothing there).

**Comment by taniaprocha** [comment]
> ok. I have some concerns regarding this section, maybe this needs to be discussed with inês as well.
> 
> 1. how is this working in terms of accessibility?
> 2. On mobile, you don't normally click on images unless they look like having some kind of interaction. Personally I would never click on one.

Ok, good point. Services and cards are buttons in the code but you're right, in mobile they should seem like buttons. @ines-silva what do you think?

**Comment by ines-silva** [comment]
This is a concern I also thought about, and I think we could have something saying "click me" floating on that section. What do you think?

**Comment by filipebfernandes** [comment]
IMO it's not worth the extra clicks to show this information. It is a critical section on our website and I would prefer it to be always available. As an example, I would prefer to have it in front of the images with some opacity.

**Comment by ines-silva** [comment]
What do you think of this? https://www.figma.com/proto/gVZQxOm1RgmaBFZJV3KL9Bmj/Aurora-Website-WIP?node-id=1086%3A132&viewport=-6987%2C641%2C0.3685816824436188&scaling=min-zoom

**Comment by filipebfernandes** [comment]
I like it, I think it's ways simpler to the user

**Comment by ines-silva** [comment]
I agree. updated on figma

**Comment by taniaprocha** [comment]
> I agree. updated on figma

No animation? They are static, right?

**Comment by filipebfernandes** [comment]
@taniaprocha from the design the `Code` section should be placed on the left following the alternate positioning of elements. Also, if you click on one of these sections they disappear

**Comment by taniaprocha** [comment]
> @taniaprocha from the design the `Code` section should be placed on the left following the alternate positioning of elements. Also, if you click on one of these sections they disappear

Thanks ✅

**Comment by filipebfernandes** [comment]
I think mobile looks good. On Desktop I still have mixed feelings about the user moving from image  to image to see information @ines-silva.

@taniaprocha don't know if it's specific to this PR but I found these issues

Screenshot 2020-06-09 at 15 11 13
Screenshot 2020-06-09 at 15 11 29

**Comment by taniaprocha** [comment]
We're discussing them on Diogo board week 5. I've just added you.

**Pull request merged**
